schema = "avalon-core:config-1.0"

[[apps]]
name = "maya2015"
label = "Autodesk Maya 2015"

[[apps]]
name = "maya2016"
label = "Autodesk Maya 2016"

[[apps]]
name = "maya2017"
label = "Autodesk Maya 2017"

[[apps]]
name = "nuke10"
label = "The Foundry Nuke 10.0"

[[tasks]]
name = "modeling"

[[tasks]]
name = "rendering"

[[tasks]]
name = "animation"

[[tasks]]
name = "rigging"

[[tasks]]
name = "lookdev"

[[tasks]]
name = "layout"

[template]
work = "{root}/{project}/{silo}/{asset}/work/{task}/{app}"
publish = "{root}/{project}/{silo}/{asset}/publish/{subset}/v{version:0>3}/{subset}.{representation}"
